name: Lint with SwiftLint

on:
  pull_request:
    paths:
      - '.github/workflows/linting.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  push:
    branches:
      - senpai
    paths:
      - '.github/workflows/linting.yml'
      - '.swiftlint.yml'
      - '**/*.swift'
  workflow_dispatch:

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
        env:
          WORKING_DIRECTORY: Harbor
